driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: gemrc-global
    run_list:
      - recipe[test_rubygems::gemrc_global]
  - name: gemrc-local
    run_list:
      - recipe[test_rubygems::gemrc_local]
  - name: gemrc-explicit-path
    run_list:
      - recipe[test_rubygems::gemrc_explicit_path]
  - name: gemrc-local-merge
    run_list:
      - recipe[test_rubygems::gemrc_local_merge]
  - name: bundle-config
    run_list:
      - recipe[test_rubygems::bundle_config]
