sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
    - chefdk
    - libgecode-dev
    - coreutils

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  global:
  - USE_SYSTEM_GECODE=true
  matrix:
  - INSTANCE=gemrc-global-ubuntu-1404
  - INSTANCE=gemrc-global-ubuntu-1604
  - INSTANCE=gemrc-global-centos-6
  - INSTANCE=gemrc-global-centos-7
  - INSTANCE=gemrc-local-ubuntu-1404
  - INSTANCE=gemrc-local-ubuntu-1604
  - INSTANCE=gemrc-local-centos-6
  - INSTANCE=gemrc-local-centos-7
  - INSTANCE=gemrc-explicit-path-ubuntu-1404
  - INSTANCE=gemrc-explicit-path-ubuntu-1604
  - INSTANCE=gemrc-explicit-path-centos-6
  - INSTANCE=gemrc-explicit-path-centos-7
  - INSTANCE=gemrc-local-merge-ubuntu-1404
  - INSTANCE=gemrc-local-merge-ubuntu-1604
  - INSTANCE=gemrc-local-merge-centos-6
  - INSTANCE=gemrc-local-merge-centos-7
  - INSTANCE=bundle-config-ubuntu-1404
  - INSTANCE=bundle-config-ubuntu-1604
  - INSTANCE=bundle-config-centos-6
  - INSTANCE=bundle-config-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
